FROM centos:7

LABEL org.label-schema.vcs-url="https://github.com/samkos/kslhub" \
      org.label-schema.docker.cmd="docker-compose up -d" \
      org.label-schema.name="kslhub" \
      org.label-schema.description="kslhub on CentOS 7" \
      maintainer="Samuel KORTAS"


RUN yum makecache fast \
    && yum -y install epel-release \
    && yum -y install \
           wget \
           bash-completion \
	   bzip2 \
           perl \
           gcc \
           gcc-c++\
           vim-enhanced \
           git \
           make \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN cd / \
    && git clone https://github.com/samkos/kslhub.git

RUN cd /kslhub \
    && git pull \
    && . ./Install_here.sh

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint_all_in_one.sh

EXPOSE 8000

ENTRYPOINT gosu munge /usr/sbin/munged \
    && echo "---> Starting the Slurm Controller Daemon (slurmctld) ..." \
    && exec gosu slurm /usr/sbin/slurmctld -Dvvv \
    && echo "---> Starting the Slurm Node Daemon (slurmd) ..." \
    && exec /usr/sbin/slurmd \
    && echo "---> Starting kslhub ..." \
    && cd /kslhub/INSTALL \
    && bash  Run_kslhub.sh 


