FROM  centos/mysql-57-centos7

ARG SLURM_VERSION=17.02.11
ARG SLURM_DOWNLOAD_MD5=b32f4260a921d335a2d52950593f0a29
ARG SLURM_DOWNLOAD_URL=https://download.schedmd.com/slurm/slurm-17.02.11.tar.bz2
ARG  MYSQL_DATABASE=slurm_acct_db
ARG      MYSQL_USER=slurm
ARG MYSQL_PASSWORD=password


ARG GOSU_VERSION=1.10

RUN yum makecache fast \
    && yum -y install epel-release \
    && yum -y install \
           wget \
           bzip2 \
           perl \
           gcc \
           gcc-c++\
           vim-enhanced \
           git \
           make \
           munge \
           munge-devel \
           python-devel \
           python-pip \
           python34 \
           python34-devel \
           python34-pip \
           mariadb-server \
           mariadb-devel \
           psmisc \
           bash-completion \
	   openssh-server \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN pip install Cython nose \
    && pip install Cython nose

RUN set -x \
    && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
#    && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
#    && export GNUPGHOME="$(mktemp -d)" \
#    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
#    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
#    && rm -rf $GNUPGHOME /usr/local/bin/gosu.asc \
    && chmod +x /usr/local/bin/gosu \
    && gosu nobody true

RUN groupadd -r slurm --gid=995 && useradd -r -g slurm --uid=995 slurm

RUN set -x \
    && wget -O slurm.tar.bz2 "$SLURM_DOWNLOAD_URL" \
    && echo "$SLURM_DOWNLOAD_MD5" slurm.tar.bz2 | md5sum -c - \
    && mkdir /usr/local/src/slurm \
    && tar jxf slurm.tar.bz2 -C /usr/local/src/slurm --strip-components=1 \
    && rm slurm.tar.bz2 \
    && cd /usr/local/src/slurm \
    && ./configure --enable-debug --prefix=/usr --sysconfdir=/etc/slurm \
        --enable-multiple-slurmd --with-mysql_config=/usr/bin  --libdir=/usr/lib64 \
    && make install \
    && install -D -m644 etc/cgroup.conf.example /etc/slurm/cgroup.conf.example \
    && install -D -m644 etc/slurm.conf.example /etc/slurm/slurm.conf.example \
    && install -D -m644 etc/slurm.epilog.clean /etc/slurm/slurm.epilog.clean \
    && install -D -m644 etc/slurmdbd.conf.example /etc/slurm/slurmdbd.conf.example \
    && install -D -m644 contribs/slurm_completion_help/slurm_completion.sh /etc/profile.d/slurm_completion.sh \
    && cd \
    && rm -rf /usr/local/src/slurm \
    && mkdir /etc/sysconfig/slurm \
        /var/spool/slurmd \
        /var/run/slurmd \
        /var/run/slurmdbd \
        /var/lib/slurmd \
        /var/log/slurm \
        /data \
    && touch /var/lib/slurmd/node_state \
        /var/lib/slurmd/front_end_state \
        /var/lib/slurmd/job_state \
        /var/lib/slurmd/resv_state \
        /var/lib/slurmd/trigger_state \
        /var/lib/slurmd/assoc_mgr_state \
        /var/lib/slurmd/assoc_usage \
        /var/lib/slurmd/qos_usage \
        /var/lib/slurmd/fed_mgr_state \
    && chown -R slurm:slurm /var/*/slurm* \
    && /sbin/create-munge-key

RUN yum -y install mysql-server mysql pwgen supervisor net-tools

# RUN mysql_install_db && chown -R mysql:mysql /var/lib/mysql  /usr/bin/mysqld_safe




#ADD ./start.sh /start.sh
ADD ./config_mysql.sh /config_mysql.sh
#ADD ./supervisord.conf /etc/supervisord.conf

# RUN echo %sudo	ALL=NOPASSWD: ALL >> /etc/sudoers

#RUN chmod 755 /start.sh
RUN chmod 755 /config_mysql.sh
RUN /config_mysql.sh

EXPOSE 3306


# RUN useradd  -r -g users --uid=1001 hub && mkdir -p /home/hub && chown -R hub.users /home/hub \
#     && useradd -r -g users --uid=1002 bob && mkdir -p /home/bob && chown -R bob.users /home/bob \
#     && useradd -r -g users --uid=1003 alice && mkdir -p /home/alice && chown -R alice.users /home/alice

# RUN echo hub:hub | chpasswd 
# RUN echo bob:bob | chpasswd 
# RUN echo alice:alice | chpasswd 

COPY slurm_five_in_one.conf /etc/slurm/slurm.conf
COPY slurmdbd.conf /etc/slurm/slurmdbd.conf

EXPOSE 8000
EXPOSE 22

# WORKDIR /home/hub

# RUN echo hi
# RUN gosu hub git clone https://github.com/samkos/kslhub.git 

# COPY Install_here_debug.sh /home/hub/kslhub/scripts/Install_here.sh

# WORKDIR /home/hub/kslhub

# RUN chown -R hub.users /home/hub \
#     && gosu hub bash  ./scripts/Install_here.sh



# RUN /usr/bin/ssh-keygen -A


# RUN cat /home/hub/kslhub/kslhub_init_env.sh >> /home/hub/.bashrc \
#     && echo . /home/hub/.bashrc > /home/hub/.profile

# RUN chown -R hub.users /home/hub/.bashrc /home/hub/.profile 



ENTRYPOINT /bin/sh -c "echo `tail -1 /etc/hosts | sed 's/kslhub/c1 c2 c3 c4 c5/'` >> /etc/hosts" \
    && gosu munge /usr/sbin/munged \
    && gosu slurm /usr/sbin/slurmctld  \
    && gosu slurm /usr/sbin/slurmdbd  \
    && gosu slurm slurmd -N c1 \
    && gosu slurm slurmd -N c2  \
    && gosu slurm slurmd -N c3  \
    && gosu slurm slurmd -N c4  \
    && gosu slurm slurmd -N c5  \	
    && /usr/sbin/sshd \
    && echo sleeping for 10000s \
    && exec /usr/bin/sleep 10000
# #   && exec gosu hub bash -c '. ./kslhub_init_env.sh && kslhub -f docker_slurm'

