FROM centos:7

LABEL org.label-schema.vcs-url="https://github.com/samkos/kslhub" \
      org.label-schema.docker.cmd="docker-compose up -d" \
      org.label-schema.name="kslhub" \
      org.label-schema.description="kslhub on CentOS 7" \
      maintainer="Samuel KORTAS"


RUN yum makecache fast \
    && yum -y install epel-release \
    && yum -y install \
           wget \
           bash-completion \
	   bzip2 \
           perl \
           gcc \
           gcc-c++\
           vim-enhanced \
           git \
           make \
    && yum clean all \
    && rm -rf /var/cache/yum

RUN cd / \
    && git clone https://github.com/samkos/kslhub.git

RUN cd /kslhub \
    && git pull \
    && . ./Install_here.sh

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh


ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
