# Copyright (c) 2017, Oracle and/or its affiliates. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
FROM centos:7


# Install server
#RUN yum install -y https://repo.mysql.com/mysql-community-minimal-release-el7.rpm \
#      https://repo.mysql.com/mysql-community-release-el7.rpm \
RUN yum install -y \
         mysql-devel \
	 mysql-server \	
         libpwquality \
  && yum clean all \
  && mkdir /docker-entrypoint-initdb.d

COPY configure_mysql.sh /configure_mysql.sh
COPY healthcheck.sh /healthcheck.sh


RUN /configure_mysql.sh


HEALTHCHECK CMD /healthcheck.sh
EXPOSE 3306 33060



CMD ["mysqld"]

