# Copyright (c) 2017, Oracle and/or its affiliates. All rights reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

#FROM oraclelinux:7-slim
FROM centos:7

ARG MYSQL_SERVER_PACKAGE=mysql-community-server-8.0.15
ARG MYSQL_SHELL_PACKAGE=mysql-shell-8.0.15
ARG MYSQL_DEVEL_PACKAGE=mysql-community-devel-8.0.15

# Install server
RUN yum install -y https://repo.mysql.com/mysql-community-release-el7.rpm \
  && yum-config-manager --enable mysql80-server \
  && yum install -y \
      $MYSQL_SERVER_PACKAGE	\
      $MYSQL_SHELL_PACKAGE \
      $MYSQL_DEVEL_PACKAGE \
      libpwquality \
  && yum clean all \
  && mkdir /docker-entrypoint-initdb.d

#      $MYSQL_SERVER_PACKAGE \


VOLUME /var/lib/mysql



# ARG SLURM_VERSION=17.02.11
# ARG SLURM_DOWNLOAD_MD5=b32f4260a921d335a2d52950593f0a29
# ARG SLURM_DOWNLOAD_URL=https://download.schedmd.com/slurm/slurm-17.02.11.tar.bz2

# ARG GOSU_VERSION=1.10

# RUN yum -y install \
#            wget \
#            bzip2 \
#            perl \
#            gcc \
#            gcc-c++\
#            vim-enhanced \
#            git \
#            make \
#            munge \
#            munge-devel \
#            python-devel \
#            python-pip \
#            python34 \
#            python34-devel \
#            python34-pip \
#            psmisc \
#            bash-completion \
# 	   openssh-server \
#     && yum clean all \
#     && rm -rf /var/cache/yum




# RUN set -x \
#     && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
# #    && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
# #    && export GNUPGHOME="$(mktemp -d)" \
# #    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
# #    && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
# #    && rm -rf $GNUPGHOME /usr/local/bin/gosu.asc \
#     && chmod +x /usr/local/bin/gosu \
#     && gosu nobody true

# RUN groupadd -r slurm --gid=995 && useradd -r -g slurm --uid=995 slurm

# RUN set -x \
#     && wget -O slurm.tar.bz2 "$SLURM_DOWNLOAD_URL" \
#     && echo "$SLURM_DOWNLOAD_MD5" slurm.tar.bz2 | md5sum -c - \
#     && mkdir /usr/local/src/slurm \
#     && tar jxf slurm.tar.bz2 -C /usr/local/src/slurm --strip-components=1 \
#     && rm slurm.tar.bz2 \
#     && cd /usr/local/src/slurm \
#     && ./configure --enable-debug --prefix=/usr --sysconfdir=/etc/slurm \
#         --enable-multiple-slurmd --with-mysql_config=/usr/bin  --libdir=/usr/lib64 \
#     && make install \
#     && install -D -m644 etc/cgroup.conf.example /etc/slurm/cgroup.conf.example \
#     && install -D -m644 etc/slurm.conf.example /etc/slurm/slurm.conf.example \
#     && install -D -m644 etc/slurm.epilog.clean /etc/slurm/slurm.epilog.clean \
#     && install -D -m644 etc/slurmdbd.conf.example /etc/slurm/slurmdbd.conf.example \
#     && install -D -m644 contribs/slurm_completion_help/slurm_completion.sh /etc/profile.d/slurm_completion.sh \
#     && cd \
#     && rm -rf /usr/local/src/slurm \
#     && mkdir /etc/sysconfig/slurm \
#         /var/spool/slurmd \
#         /var/run/slurmd \
#         /var/run/slurmdbd \
#         /var/lib/slurmd \
#         /var/log/slurm \
#         /data \
#     && touch /var/lib/slurmd/node_state \
#         /var/lib/slurmd/front_end_state \
#         /var/lib/slurmd/job_state \
#         /var/lib/slurmd/resv_state \
#         /var/lib/slurmd/trigger_state \
#         /var/lib/slurmd/assoc_mgr_state \
#         /var/lib/slurmd/assoc_usage \
#         /var/lib/slurmd/qos_usage \
#         /var/lib/slurmd/fed_mgr_state \
#     && chown -R slurm:slurm /var/*/slurm* \
#     && /sbin/create-munge-key



# ##########################################################################################
# # general preparation
# ##########################################################################################

# RUN /usr/bin/ssh-keygen -A
# EXPOSE 22


# RUN pip install Cython nose \
#     && pip install Cython nose

# RUN set -x \
#     && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-amd64" \
#     && chmod +x /usr/local/bin/gosu \
#     && gosu nobody true



COPY configure_mysql.sh /configure_mysql.sh
COPY healthcheck.sh /healthcheck.sh
ENTRYPOINT ["/configure_mysql.sh"]
HEALTHCHECK CMD /healthcheck.sh
EXPOSE 3306 33060







CMD ["mysqld"]

